### ISSUE TITLE
Plugin blocks redirects from Geomate

### ISSUE THREAD

**Issue by Radu033** [putyourlightson/craft-blitz#420]
I installed the blitz pluigin after the Geomate configurations. Before Blitz, everything worked fine with Geomate, now after I installed Blitz, Geomate doesn't redirect to the correct language anymore.

Is there a way to fix that?

Craft Version: 3.7.44
Blitz - up to date
Geomate - up to date

**Comment by bencroker** [comment]
If using server rewrites in Blitz, a redirect will kick in before Geomate has had a chance to do its thing. Removing the server rewrites should solve this for you.

**Comment by Radu033** [comment]
Hey @bencroker  thanks for the answer. How can I disable the server redirects in Blitz? I can't find this option nowhere in the CP.

**Comment by bencroker** [comment]
See https://putyourlightson.com/plugins/blitz#server-rewrites

**Comment by Radu033** [comment]
I tried the .htaccess change but it still doesn't work.

Here is a screenshot of my .htaccess
https://prnt.sc/vrY2xvamKYSX

And a screenshot of my Blitz Query setting
https://prnt.sc/Ux5Cv22niJLn

Is there something else I could try?

P.S. I refreshed the cache before testing.

**Comment by bencroker** [comment]
It looks like the Blitz cache rewrite is still in place...?

![Screenshot 2022-06-09 at 12 11 07](https://user-images.githubusercontent.com/57572400/172823326-26971129-12a5-4d91-8bf8-5f46298753bb.png)

**Comment by Radu033** [comment]
I removed the code from .htaccess file
[image: image.png]

But it still doesn't work. I Flushed all the cache, and tried it with
multiple browsers and it still doesn't work.

Is there something I'm doing wrong?

**Comment by bencroker** [comment]
Please send a URL to info@putyourlightson.com, along with steps to reproduce, and I'll take a closer look.

**Comment by bencroker** [comment]
This issues was resolved via email and unrelated to Blitz: `autoRedirectEnabled` was set to `false` when it should have been set to `true` to make redirects work as per https://github.com/vaersaagod/geomate#autoredirectenabled-bool
